version: "3.9"
services:
  db_postgres:
    container_name: postgres
    image: postgres:13
    volumes:
      - pgdata:/var/lib/postgresql/data/
    ports:
        - 5436:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USERNAME=postgres
      - POSTGRES_DB=point_of_sale
    networks: 
      - go_microservice
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "5000"
    restart: "always"
    #env_file:
     # - .env
    environment:
      - PORT=5000
      - GIN_MODE=release
      - DB_HOST=db_postgres
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=point_of_sale
      - DB_PORT=5432
      - TOKEN_TTL=36000
      - JWT_PRIVATE_KEY=pointofsale
    depends_on:
      - db_postgres
    networks:
      - go_microservice
      - "api.network"
    deploy:
      replicas: 5
  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on: 
      - api
    ports: 
      - "80:80"
    networks: 
      - "api.network"
networks:
  api.network:
    name: api.network
  go_microservice:
    name: go_microservice
volumes:
  pgdata:
    name: pgdata